### PR TITLE
Fixed reverse DNS range infinite loop in crobat client

### PR DESCRIPTION
**Pull request by rwincey**
There is an infinite loop bug in the crobat client when performing a ranged-based reverse lookup. i.e. 127.0.0.1/32.

### CODE REVIEW

**Comment by reconsec** [comment]
I should have split this up but the second commit allows for the return of the IP address as part of the returned object for a reverse lookup. Keeps the user from having to perform a forward lookup up on completion of the request to get the IP for the domain.

**Comment by rwincey** [comment]
This pull request also has a change to return the IP address along with the domain when performing a reverse lookup.

**Comment by Cgboal** [comment]
Cool looks good. Thank you.

**Comment by rwincey** [comment]
Awesome :)  What's the usual timeframe before the new version will make it into the public server?

**Comment by Cgboal** [comment]
The client is updated now, just update your installation. For the server-side, i'll do it some time this week. Your change to add the IPv4 address to the response for reverse DNS will need some other changes made to support it though. It's not in the gRPC protobuf spec, and it's not handled at all by the client. I'll sort this when I do the deployment.

**Comment by Cgboal** [comment]
I'll add support for it in the client when I do the deployment.

**Comment by rwincey** [comment]
Ya, I have code for the gRPC client in my fork but I didn't add it because I didn't know how you'd prefer the output. Thanks for the help. :)

**Pull request merged**
